### ISSUE TITLE
feature: print module/class summary without method descriptions on same page

### ISSUE THREAD

**Issue by maeddlae** [Chilipp/autodocsumm#15]
The idea is that one can use 

```python
.. autoclass:: module.Class
    :autosummary:
```
which prints the class docstring and the autodocsummary. Today, autodocsumm does not print anything, because there are no methods documented. This means, the class methods must be documented somewhere else, maybe in another rst. I don't know if this is possible.

The result would be something like this: http://pandas.pydata.org/pandas-docs/stable/reference/series.html#missing-data-handling

**Comment by Chilipp** [comment]
Interesting idea, thanks! Yes, this should be easy to include. I'll have a look into it
