### ISSUE TITLE
sub classes appear as miscellaneous

### ISSUE THREAD

**Issue by maeddlae** [Chilipp/autodocsumm#16]
- If a class defines a subclass, the subclass appear in summary chapter "miscellaneous"
- And in autodocsumm, it says "miscallaneous", which is wrong. Correct: "Miscellaneous"

**Comment by Chilipp** [comment]
Hi @maeddlae! Thanks again for your report! Could you please be a bit more explicit? Because I could not reproduce this problemDo I get you right, that if you have something like

```python

class A:
    "Doc of A"
    pass

class B(A):
    "Doc of B"
    pass

```

in a file named `test.py`, then `B` appears under the `miscellaneous` section in

```
.. automodule:: test
    :autosummary:
    :members:
```
?

**Comment by maeddlae** [comment]
Sorry for answering that late. I didn't see your question earlier. Here is an example:

```python
class A():
    """
    Class A docstring
    """    
    class SubClassOfA():
        """
        Class SubClassOfA docstring
        """
    
        def __init__(self):
            """
            Init of class SubClassOfA
            """
            pass
        
    def __init__(self):
        """
        Init of class A
        """
        pass
    
    def met1(self):
        """
        Method 1 of class A
        """
        pass
```

The generated API then looks like this:
![image](https://user-images.githubusercontent.com/4435096/60661151-a4763900-9e59-11e9-8f0c-e6a23baea3e7.png)

**Comment by Chilipp** [comment]
Hi @maeddlae! Thanks for the clarification 😄 As workaround, you can define your own grouper in `conf.py`, for example

```python
def grouper(app, what, name, obj, section, parent):
    if isinstance(obj, type) and isinstance(parent, type):
        return "Class"

def setup(app):
    app.connect('autodocsumm-grouper', grouper)
```

However, we can also change the current behaviour of autodocsumm. Any suggestion, under which section the `SubClassOfA` should appear? Maybe *Member classes*?

**Comment by maeddlae** [comment]
Hmm, I would say just "Class" would be ok. But Python calls them "Inner Class" or "Nested Class", see https://pythonspot.com/inner-classes/.

**Comment by Chilipp** [comment]
Agreed. I just implemented the necessary changes in https://github.com/Chilipp/autodocsumm/pull/17 which then closes this issue. Would you mind confirming that it full fills the request?
