### ISSUE TITLE
`*` escaped too much

### ISSUE THREAD

**Issue by coldfix** [Chilipp/autodocsumm#2]
Hey,

lovely tool!

I found that signatures with `*args` or `**kwargs` show up weird in final html output, displayed as `\*args` with visible backslash.

It works as expected if removing the line `sig = sig.replace('*', r'\*')`.

**Comment by Chilipp** [comment]
Thank you very much @coldfix, you are completely right, this line is redundant.  I removed it in https://github.com/Chilipp/autodocsumm/pull/3 and implemented a few tests to make sure that this does not occur anymore.

**Comment by Chilipp** [comment]
All right @coldfix: I just pushed a new release [0.1.8](https://github.com/Chilipp/autodocsumm/releases/tag/v0.1.8) to [PyPi](https://pypi.org/project/autodocsumm/) (conda-forge will come later today) that includes the fix in https://github.com/Chilipp/autodocsumm/pull/3. Thanks again for reporting this issue and for using autodocsumm!

Best,
Philipp

**Comment by coldfix** [comment]
Thanks a lot! :)
