### ISSUE TITLE
module-level summary location affected by headers in module docstring

### ISSUE THREAD

**Issue by jbloom** [Chilipp/autodocsumm#21]
Everything with `autodocsumm` works great I have a module with a docstring like this:
```
"""
========
mymodule
========

Here is a summary of module.

"""
```
When I build the sphinx docs, I get my module level docstring followed by the summary (table of contents) for the module.

But if the module-level docstring looks like this:
```
"""
=========
mymodule2
=========

Subheading
-------------
Some stuff
"""
```
then when I build the sphinx docs, the summary (table of contents) appears **before** the module-level doc string--which looks strange and doesn't really make sense.

**Comment by Chilipp** [comment]
Hi @jbloom! My apologies for being so silent! I resolved this ambiguity with #28 and it's now always behind the module-level docstring
