### ISSUE TITLE
Warnings is deprecated

### ISSUE THREAD

**Issue by gigiogigo** [Chilipp/autodocsumm#24]
Hello, I find this extension very useful thanks for the work!

While executing it the following warning comes up:
> autodocsumm\__init__.py:498: RemovedInSphinx40Warning: Autosummary.warnings is deprecated
>  return self.warnings + dn + doc_nodes

The error comes from the following line:
https://github.com/Chilipp/autodocsumm/blob/edba002f8e6bf1c63ac35bbffcd40147e7806685/autodocsumm/__init__.py#L498

In the following page you can check that the warnings are deprecated: https://www.sphinx-doc.org/en/master/extdev/deprecated.html

I hope this helps :).

**Comment by Chilipp** [comment]
Thanks @gigiogigo for reporting this! I implemented some changes and tests in #25, so this should be resolved now. If not, please reopen this issue :smiley:

**Comment by gigiogigo** [comment]
I just upgraded using the `pip3 install --upgrade git+https://github.com/Chilipp/autodocsumm` and I didn't get the warning anymore!
I also tried looking for the update via `pip3 list --outdated` but it didn't show up, maybe the push to pypi takes more time...

Thanks a lot for fixing it so quickly! I'm glad I could help 😄 .

**Comment by Chilipp** [comment]
Thanks for the confirmation! 

> I also tried looking for the update via pip3 list --outdated but it didn't show up, maybe the push to pypi takes more time...

Yes, I did not do a new release immediately. But now, it is available on [PyPi](https://pypi.org/project/autodocsumm/) and [conda-forge](https://anaconda.org/conda-forge/autodocsumm) will come later today.
