### ISSUE TITLE
f-strings not supported in python 3.5

### ISSUE THREAD

**Issue by scottgigante** [Chilipp/autodocsumm#30]
By including f-strings in the latest release (https://github.com/Chilipp/autodocsumm/blob/master/autodocsumm/__init__.py#L530), autodocsumm is no longer compatible with python 3.5, despite the badge in the README saying it is. I suggest you either remove 3.5 from the badge and add a `python_requires=">=3.6"` to setup.py, or use `str.format` instead.

**Comment by Chilipp** [comment]
thanks for reporting this @scottgigante! I made the necessary chances in #31 and merge it when the CI passes

**Comment by scottgigante** [comment]
Thanks @Chilipp !

**Comment by Chilipp** [comment]
FYI @scottgigante, the new release solving this issue is now available via `pip` and `conda-forge`

**Comment by scottgigante** [comment]
Thank you! Appreciate your rapid response.
