### ISSUE TITLE
Warning when building documentation with v0.2.0 or v0.2.1

### ISSUE THREAD

**Issue by bouweandela** [Chilipp/autodocsumm#32]
Since version 0.2 of autodocsumm, we are seeing the following warning when building our documentation:
```
some_module.py:docstring of some_module.some_function:1:<autosummary>:1: WARNING: Inline emphasis start-string without end-string.
```
The warning appears in files that have
```python
from itertools import product
```
at the top. I suspect it has something to do with the asterisk in the first argument of [itertools.product](https://docs.python.org/3.8/library/itertools.html#itertools.product) (it's `*iterables`), but I'm not sure. My apologies for the slightly vague bug report, if there's any way in which I can make it more clear, please let me know.

**Comment by Chilipp** [comment]
hi @bouweandela! thanks for reporting this! Could you simply post a python module file that you think reproduces this bug? Then I can make a small setup with sphinx to test it.

**Comment by bouweandela** [comment]
Here is a fairly minimal example:

I generated a default sphinx configuration using `sphinx-quickstart` and added the following to conf.py:
```
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).absolute().parent))

extensions = [
    "sphinx.ext.autodoc",
    "autodocsumm",
]

autodoc_default_options = {
    "members": True,
    "autosummary": True,
}
```
content of test.py:
```
from itertools import product
```
content of index.rst:
```
.. automodule:: test
```
