### ISSUE TITLE
Missing declared dependency on `six` needs resolution

### ISSUE THREAD

**Issue by sirosen** [Chilipp/autodocsumm#35]
I understand that it's probably still desirable to support py2 in this project, but as some projects move to py3 only its becoming possible to have a package which doesn't depend on `six` 😲 !

Anyway, I think `autodocsumm` should either

A) add `six` to its dependencies (no version, I think)
or
B) treat `six` being absent as "automatic PY3 mode"

I haven't looked at the code yet, but my inclination would be to add

```python
# _compat.py

try:
    import six
except ImportError:
    PY3 = True
else:
    PY3 = six.PY3
```

and see what else needs wrapping. I can submit a PR if that would be interesting.

**Comment by Chilipp** [comment]
thanks for bringing this up @sirosen! I think we can remove it entirely as sphinx is nowadays python3 only, too. I can fix this today

**Comment by sirosen** [comment]
Awesome! I just stumbled over this today, so now I'm thinking about using it myself.
Thanks for helping to make sphinx that much better to work with.
