### ISSUE TITLE
Feature request: option to set ":nosignatures:" for autosummary

### ISSUE THREAD

**Issue by dgilland** [Chilipp/autodocsumm#43]
Would be useful to be able to specify the `:nosignatures:` option for the autosummary to disable exception/class/function signatures. I'm currently resorting to monkey-patching `AutosummaryDocumenter.add_autosummary` to inline the option globally.

**Comment by Chilipp** [comment]
Hey @dgilland! Sounds like a good approach to me! Sorry for getting back to you so late, it took a while to find some time for me to become up-to-date with the latest developments in sphinx. I just released a new version that is compatible with sphinx 3.4 and 3.5.

Would you be willing to provide a PR to add the `:nosignatures:` option?

**Comment by dgilland** [comment]
@Chilipp I've opened a PR to add this: #46

**Comment by ycremar** [comment]
Thank you @dgilland and @Chilipp for the new feature. It works great! I was just looking for solutions and found it updated here. I wonder if the new feature is updated on PyPI cuz directly installing it from pip seems not working (but `pip install git+` from this repo works).

**Comment by Chilipp** [comment]
Hey @ycremar ! I'll make a new release asap. There is an issue with the docs on RTD and I'll first need to figure how to fix this.

https://readthedocs.org/projects/autodocsumm/builds/13526310/

**Comment by Chilipp** [comment]
Closed via #46. The issue with the docs is tracked in #47
