### ISSUE TITLE
Crash when encountering class attributes that are aliases

### ISSUE THREAD

**Issue by IljaManakov** [Chilipp/autodocsumm#44]
Hi,

I have encountered an issue where autodocsumm crashes when it encounters a class attribute that is a type instance (i.e. it is just an alias). What appears to happen is the following:
- autodoc's ClassCodumenter's get_doc returns None for aliases.
- AutoSummary's get_grouped_documenters attempts to iterate over the return value of get_doc
- Combined, this results in a TypeError when a class has a type instance as an attribute

[minimal-example.zip](https://github.com/Chilipp/autodocsumm/files/6221292/minimal-example.zip)

**Comment by EpicWink** [comment]
Fixed by #42

**Comment by Chilipp** [comment]
Thanks for reporting @IljaManakov! This issue has been closed via #42.
