### ISSUE TITLE
Type annotations are not rendered properly

### ISSUE THREAD

**Issue by greyli** [Chilipp/autodocsumm#62]
Hi, thanks for the cool project. It seems that the type annotations for the class arguments are not rendered properly. Catch this in Marshmallow docs: https://marshmallow.readthedocs.io/en/stable/marshmallow.validate.html

Take the first `And` class as an example. Here is the raw definition:

```py
And(*validators: Callable[[Any], Any], error: Optional[str] = None)
```

Expected output:

```py
And(*validators, error)
```

Actual output:

```py
And(*validators, Any], error)
```

- sphinx==4.1.2
- autodocsumm==0.2.6

**Comment by Chilipp** [comment]
Hey @greyli ! Thanks for your input! Indeed, that does not make sense. I wonder, whether this is a problem of autodocsumm or autosummary.

What do you get when you include

```
.. autosummary::

    marshmallow.validate.And
```

?

**Comment by greyli** [comment]
It's the same as the old output:

![image](https://user-images.githubusercontent.com/12967000/129859027-41eb00bf-4655-425d-bb2f-07db925b37ea.png)

Source: https://github.com/marshmallow-code/marshmallow/blob/dev/docs/marshmallow.validate.rst

I think this may be related to https://github.com/sphinx-doc/sphinx/issues/6311, but that issue seems fixed by https://github.com/sphinx-doc/sphinx/pull/6353. Do you think I should report it to Sphinx? I'm a bit confused with autosummary and autodocsumm, sorry.

**Comment by Chilipp** [comment]
hey @greyli! yes, this is definitely an issue for the sphinx-doc repository and you should make sure that you use the latest version of sphinx.

I am closing this then.

**Comment by greyli** [comment]
I see, thanks!
