### ISSUE TITLE
Missing upper bound on sphinx version for `autodocsumm==2.2.x`

### ISSUE THREAD

**Issue by eivindjahren** [Chilipp/autodocsumm#63]
A missing upper bound on version 2.2.x is causing downstream package `sphinx-toolbox` to incorrectly install `autodocsumm=2.2.0` together with `sphinx>=4`. 

see https://github.com/sphinx-toolbox/sphinx-toolbox/issues/71

**Comment by Chilipp** [comment]
thanks for pointing to this @eivindjahren! should be fixed by #64
