### ISSUE TITLE
 No links to items in summary tables when using __init__.py imports

### ISSUE THREAD

**Issue by raymanP** [Chilipp/autodocsumm#65]
Hi dears,
if having an module import in \_\_init__.py the links are missing for the class.
Sphinx is showing the links correctly, .e.g. for :meth:\`mymodule.myclass.mymethod\` for the below example.

Example:
* mymodule/\_\_init__.py
`from mymodule.mysubmodule import myclass`

* mymodule/mysubmodule.py
```
class myclass():
    def mymethod(self):
        """my doc"""
```

* doc.rst
```
.. currentmodule:: mymodule.myclass

.. autoclasssumm:: myclass
    :autosummary-members:
```

**Comment by Chilipp** [comment]
hey @raymanP! I wonder what you get with

```
.. autosummary::

    myclass.mymethod
```

Could you please try? I wonder whether this could be related to what I observed quite some time ago in https://github.com/sphinx-doc/sphinx/issues/9069

**Comment by raymanP** [comment]
hey @Chilipp! This also produces an entry without a link.
I already tried all possibilities I could imagine.

Classes in the same module which are not in the __init__.py are linked correctly.

**Comment by raymanP** [comment]
Great to know.. Thank you @Chilipp! Then I will wait for the upstream fix. :)

**Comment by raymanP** [comment]
Then we can close this here. Have a nice day ;)
