### ISSUE TITLE
Alias Expands Nested Class Documentation

### ISSUE THREAD

**Issue by deckar01** [Chilipp/autodocsumm#69]
Assigning a type to a class attribute is documented as an alias, but its nested class members are being expanded.

```py
class NestedClass:
    """Parent class"""
    class Foo:
        """Nested class"""
        def foo(self):
            """Nested method"""
            pass

        def bar(self):
            """Nested method"""
            pass

class Attribute:
    """Attribute"""
    #: Alias
    foo = NestedClass.Foo
    #: Attribute
    bar = 'bar'
```

<img width="721" alt="Screen Shot 2022-02-25 at 6 30 14 PM" src="https://user-images.githubusercontent.com/3108007/155820699-26a82d09-3591-4b47-9a8c-0047f1c1d11d.png">

Without autosummary on auto doc does not recurse on aliases:

<img width="326" alt="Screen Shot 2022-02-25 at 6 28 57 PM" src="https://user-images.githubusercontent.com/3108007/155820704-ea14cb71-ecc7-4b6a-95aa-c3f1415fdeda.png">

**Comment by Chilipp** [comment]
thanks for reporting @deckar01! I do have no idea so far what causes this behaviour
