### ISSUE TITLE
Instance variable not shown correctly

### ISSUE THREAD

**Issue by maeddlae** [Chilipp/autodocsumm#8]
**Description**
Instance variable is not shown correctly:

**Example**
```
class Example():
    """
    class documentation
    """
    class_variable = 12 #: This is a classvariable
    
    def __init__(self):
        """
        constructor doc
        """
        self.instance_variable = 34 #: This is an instance variable
```
Generated output:
![image](https://user-images.githubusercontent.com/4435096/57018023-f9ab8980-6c21-11e9-8c8f-bcb7709dee0c.png)

**Setup:**
- Python 3.7.1
- Sphinx 2.0.1
- autodocsumm 0.1.9
- sphinx-rtd-theme 0.4.3

**Comment by Chilipp** [comment]
Good point, yes, that is at the moment not working. The only workaround is to create a class_variable and override it in the corresponding instance

```python
class Example():
    """
    class documentation
    """
    class_variable = 12 #: This is a classvariable

    instance_variable = None #: This is an instance variable and will be overwritten
    
    def __init__(self):
        """
        constructor doc
        """
        self.instance_variable = 34 #: This is an instance variable
```

But you are right, since autodoc is able to put the `instance_variable` here, `autodocsumm` should as well

**Comment by maeddlae** [comment]
Do you plan to fix this in the near future? I am asking because autodocsumm perfectly fits my needs. But showing the attributes is critical for me..

**Comment by Chilipp** [comment]
Yes, I will work on it before Sunday. I don't think it should be too difficult.

**Comment by maeddlae** [comment]
Great, thanks a lot. Then I will wait for your update:-)
