### ISSUE TITLE
Estimated date for 0.2.9 release?

### ISSUE THREAD

**Issue by calebchiam** [Chilipp/autodocsumm#81]
Hi @Chilipp, just wanted to check if there's an estimated date of release for `v0.2.9`. One of the projects I work on relies on `autodocsumm` but would like to upgrade to `Sphinx v5.0`, which `v0.2.8` is not compatible with. (I see that `master` is compatible with `v5.0`, as of https://github.com/Chilipp/autodocsumm/pull/79.)

**Comment by Chilipp** [comment]
hey @calebchiam! I will make a new release today

**Comment by Chilipp** [comment]
it's available on PyPi now https://pypi.org/project/autodocsumm/ and conda-forge will come today

**Comment by calebchiam** [comment]
Thank you very much!
