### ISSUE TITLE
Sphinx `ObjectMember`-related deprecations

### ISSUE THREAD

**Issue by AnonymouX47** [Chilipp/autodocsumm#89]
After upgrading Sphinx from 6.1.2 to 7.2.6 (with autodocsumm 0.2.11), the following warnings are issued while building docs:

1. At https://github.com/Chilipp/autodocsumm/blob/7009e5ec0de58ac2675269829ca602447113d6e2/autodocsumm/__init__.py#L223
   ```
   RemovedInSphinx80Warning: The tuple interface of ObjectMember is deprecated. Use (obj.__name__, obj.object) instead.
     members = [(membername, member) for (membername, member) in members
   ```
2. At https://github.com/Chilipp/autodocsumm/blob/7009e5ec0de58ac2675269829ca602447113d6e2/autodocsumm/__init__.py#L230
   ```
   RemovedInSphinx80Warning: Returning tuples of (name, object) as the second return value from get_object_members() is deprecated. Return ObjectMember(name, object) instances instead.
     for (mname, member, isattr) in self.filter_members(members, want_all):
   ```

From the name of the warning class, it seems the deprecated features will be removed in Sphinx 8.0.

I checked through the [changelog](https://www.sphinx-doc.org/en/master/changes.html) but couldn't find any reference to these deprecations. Anyways, I looked a little further and found the following:

- https://github.com/sphinx-doc/sphinx/commit/6f3c5b8a2ca712dcbea38cb2a9a0529af0d9cbb5
- https://github.com/sphinx-doc/sphinx/issues/11631
- https://github.com/sphinx-doc/sphinx/pull/11651
  - particularly https://github.com/sphinx-doc/sphinx/pull/11651/commits/8f2a6f044fbd456f6fa224cf5435b652ef72ad19

From these, the deprecations seem to have started from Sphinx 7.2.0.

- - -

I tried

```diff
@@ -220,8 +220,8 @@ class AutosummaryDocumenter(object):

         # remove members given by exclude-members
         if self.options.exclude_members:
-            members = [(membername, member) for (membername, member) in members
-                       if membername not in self.options.exclude_members]
+            members = [member for member in members
+                       if member.__name__ not in self.options.exclude_members]

         # document non-skipped members
         memberdocumenters = []
```
but results in
```
AttributeError: 'tuple' object has no attribute '__name__'
```
which is honestly quite confusing since the contents of `members` seem to be `ObjectMember` instances from the deprecation warning message above.

Anyways, I'm not sure I know how to go about fixing them since I'm not quite familiar with Sphinx extension code but obviously, a proper fix will have to do with https://github.com/Chilipp/autodocsumm/blob/7009e5ec0de58ac2675269829ca602447113d6e2/autodocsumm/__init__.py#L219 and https://github.com/Chilipp/autodocsumm/blob/7009e5ec0de58ac2675269829ca602447113d6e2/autodocsumm/__init__.py#L223-L224

- - -

Also, I noticed a couple other unrelated deprecation warnings while running the tests (with Sphinx 7.2.6).

**Comment by domdfcoding** [comment]
Yes still an issue (and on Sphinx 8.0 is now an error)

**Comment by theOehrly** [comment]
@domdfcoding @AnonymouX47 can you provide an example that produces this error? 
I wanted to take a look at it but the project where I tried it did not produce that warning (or the error now).
