### ISSUE TITLE
Sorting sections in the summary

### ISSUE THREAD

**Issue by funkyfuture** [Chilipp/autodocsumm#90]
hello there, i may be over-using this extension by returning other names than "Members" and "Attributes" from a `autodocsumm-grouper` handler. the order of sections within a summary is then determined by the one in which the members were evaluated. would you be interested to include an option for sorting these sections? i suppose the most flexible would be to accept either None (default) for no sorting or a callable that is then used for the `key`-parameter of the sorting.

**Comment by Chilipp** [comment]
hey @funkyfuture! sounds good to me! would you be able to submit a PR?

**Comment by funkyfuture** [comment]
given your quick reply, i'll do that after dinner.

**Comment by Chilipp** [comment]
awsome, thanks :smiley:

**Comment by funkyfuture** [comment]
solved in #93.

**Comment by Chilipp** [comment]
thanks again @funkyfuture! I just made a new release (0.2.12) that implements the new config value from #93
